### ISSUE TITLE
Texture not being applied correctly

### ISSUE THREAD

**Issue by divya-soni-14** [iffyloop/TripoSR-Bake#4]
I'm trying to execute the sample commands given in the readme, but the final obj file generated has no texture applied to it. There is a png file generated of the texture, but I'm not sure what to do with it. Can someone help?

**Comment by iffyloop** [comment]
In whatever game engine or 3D modeling software you use (e.g. Blender), there should be an option after importing the OBJ to create/assign a material to it. When you do that, you can assign that texture to the material. Let me know if this works for you, or if not, what your use case is, and I'll try to help.
