### ISSUE TITLE
How can we get a low poly 3D objects without been helped by blender or any other engine?

### ISSUE THREAD

**Issue by joshkiller** [iffyloop/TripoSR-Bake#5]
Thank you for resolving that issue earlier. I'm interested in converting directly the mesh generetae to FBX format to use the output in a game engine, and I'd prefer that 3D models to be low-poly. Could you suggest how I might proceed with this, considering my limited experience with 3D model generation? Additionally, I'm keen to integrate TripoSR with Stable Diffusion for text-to-3D generation. Any advice on this would be greatly appreciated.

**Comment by iffyloop** [comment]
You will need to use another tool to process the mesh if you want a low-poly output. I would recommend [MeshLab](https://www.meshlab.net/) for this purpose:
1. Run the `01-mesh.py` script with the appropriate arguments
2. Open MeshLab, import the OBJ file generated by the previous script
3. In the menubar at the top of the window/screen: Filters -> Smoothing, Fairing and Deformation -> Laplacian Smooth
4. Check the Preview box and change the iterations until the mesh looks appropriately smooth without getting too thin/deformed
5. In the menubar again: Filters -> Remeshing, Simplification and Reconstruction -> Remeshing: Isotropic Explicit Remeshing
6. You can change the iterations seemingly to get various amounts of simplification, there are lots of other parameters too which I don't fully understand
7. Export the simplified (low-poly) mesh as OBJ, then use it as the input to the `02-texture.py` script
I'd like to package all of this functionality in a single application sometime soon, but for now, it is unfortunately a manual workflow. Let me know if you have any questions!
